container:
  image: node:latest

lint_task:
  environment:
    NPM_TOKEN: ENCRYPTED[0c80e17aabeafbdf97bfe0bce75a183319961a3ba181c63bd5a591731d16fc0065a19e0f595b6750d886274bc998b6fd]
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
  install_script: npm install
  test_script: npm run lint

test_task:
  environment:
    NPM_TOKEN: ENCRYPTED[0c80e17aabeafbdf97bfe0bce75a183319961a3ba181c63bd5a591731d16fc0065a19e0f595b6750d886274bc998b6fd]
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
  install_script: npm install
  test_script: npm test

coverage_task:
  env:
    NPM_TOKEN: ENCRYPTED[0c80e17aabeafbdf97bfe0bce75a183319961a3ba181c63bd5a591731d16fc0065a19e0f595b6750d886274bc998b6fd]
    CODECOV_TOKEN: ENCRYPTED[cc9756d1a2adf5cc000b12cbf976eeeea9442237b5288f81b5279d23322c6e1f6deb2d4898c60e77f239a218b8ee7fcf]
  script:
    - npm install
    - npm test
    - npm run codecov

publish_task:
  depends_on:
    - lint_task
    - test_task
  only_if: $BRANCH == "master"
  environment:
    NPM_TOKEN: ENCRYPTED[0c80e17aabeafbdf97bfe0bce75a183319961a3ba181c63bd5a591731d16fc0065a19e0f595b6750d886274bc998b6fd]
  script:
    - npm install
    - npm run build
#    - npx semantic-release
    - npm publish --access public