container:
  image: node:latest

lint_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
  install_script: npm install
  test_script: npm run lint

test_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
  install_script: npm install
  test_script: npm test

coverage_task:
  env:
    CODECOV_TOKEN: ENCRYPTED[cc9756d1a2adf5cc000b12cbf976eeeea9442237b5288f81b5279d23322c6e1f6deb2d4898c60e77f239a218b8ee7fcf]
  script:
    - npm install
    - npm test
    - npm run codecov

publish_task:
  depends_on:
    - lint_task
    - test_task
  only_if: $BRANCH == "master"
  environment:
    NPM_TOKEN: ENCRYPTED[845742743a538e14424940f88bbcdc3e4cdb18bf6ec362dad2509c06c9fb20db3a1820e04e7fcc061fc58ddd4dbf5d4a]
  script:
    - npm install
    - npm run compile
#    - npx semantic-release
    - npm publish