container:
  image: node:latest

lint_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
  install_script: npm install
  test_script: npm run lint

test_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
  install_script: npm install
  test_script: npm test

coverage_task:
  env:
    CODECOV_TOKEN: ENCRYPTED[cc9756d1a2adf5cc000b12cbf976eeeea9442237b5288f81b5279d23322c6e1f6deb2d4898c60e77f239a218b8ee7fcf]
  script:
    - npm install
    - npm test
    - npm run codecov

publish_task:
  depends_on:
    - lint_task
    - test_task
  only_if: $BRANCH == "master"
  environment:
    NPM_TOKEN: ENCRYPTED[1f53dfd5adb2f9b3e99715124a577d15b8d8142c77f11af31afa1c9c062012535d868ee4ef8d120ba8754eb2382e9128]
  script:
    - npm install
    - npm run build
#    - npx semantic-release
    - npm publish